# Reg. no: 20BAI1055
# Name: Rakesh Kumar K S
## DL Lab 1 - assignment

### Making the NN learn by updating weight

In [1]:
# We try to get the prediction to predict 0.80

In [2]:
weight = 0.5
input = 0.5
goal_prediction = 0.8
step_amount = 0.001
for iteration in range(1101):
    pred = input * weight
    error = (pred - goal_prediction) ** 2
    print("Error:" + str(error) + " Prediction:" + str(pred))

    up_pred = input * (weight + step_amount)
    up_error = (goal_prediction - up_pred) ** 2
    down_pred = input * (weight - step_amount)
    down_error = (goal_prediction - down_pred) ** 2
    if(down_error < up_error):
        weight = weight - step_amount

    if(down_error > up_error):
        weight = weight + step_amount

Error:0.30250000000000005 Prediction:0.25
Error:0.3019502500000001 Prediction:0.2505
Error:0.30140100000000003 Prediction:0.251
Error:0.30085225 Prediction:0.2515
Error:0.30030400000000007 Prediction:0.252
Error:0.2997562500000001 Prediction:0.2525
Error:0.29920900000000006 Prediction:0.253
Error:0.29866224999999996 Prediction:0.2535
Error:0.29811600000000005 Prediction:0.254
Error:0.2975702500000001 Prediction:0.2545
Error:0.29702500000000004 Prediction:0.255
Error:0.29648025 Prediction:0.2555
Error:0.29593600000000003 Prediction:0.256
Error:0.2953922500000001 Prediction:0.2565
Error:0.294849 Prediction:0.257
Error:0.29430625 Prediction:0.2575
Error:0.293764 Prediction:0.258
Error:0.2932222500000001 Prediction:0.2585
Error:0.292681 Prediction:0.259
Error:0.29214025 Prediction:0.2595
Error:0.2916 Prediction:0.26
Error:0.2910602500000001 Prediction:0.2605
Error:0.29052100000000003 Prediction:0.261
Error:0.28998225 Prediction:0.2615
Error:0.28944400000000003 Prediction:0.262
Error:0.2889

In [3]:
pred

0.7999999999999672

As we can see above, our prediction went from 0.25 to very close to 0.8, making the error nearly 0

### Trying to learn using Gradient Descent this time

In [4]:
weight = 0.5
goal_pred = 0.8
input = 0.5
for iteration in range(20):
    pred = input * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = input * delta
    weight = weight - weight_delta
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:0.30250000000000005 Prediction:0.25
Error:0.17015625000000004 Prediction:0.3875
Error:0.095712890625 Prediction:0.49062500000000003
Error:0.05383850097656251 Prediction:0.56796875
Error:0.03028415679931642 Prediction:0.6259765625
Error:0.0170348381996155 Prediction:0.669482421875
Error:0.00958209648728372 Prediction:0.70211181640625
Error:0.005389929274097089 Prediction:0.7265838623046875
Error:0.0030318352166796153 Prediction:0.7449378967285156
Error:0.0017054073093822882 Prediction:0.7587034225463867
Error:0.0009592916115275371 Prediction:0.76902756690979
Error:0.0005396015314842384 Prediction:0.7767706751823426
Error:0.000303525861459885 Prediction:0.7825780063867569
Error:0.00017073329707118678 Prediction:0.7869335047900676
Error:9.603747960254256e-05 Prediction:0.7902001285925507
Error:5.402108227642978e-05 Prediction:0.7926500964444131
Error:3.038685878049206e-05 Prediction:0.7944875723333098
Error:1.7092608064027242e-05 Prediction:0.7958656792499823
Error:9.614592036015323

As we can see, the prediction is getting closer and closer to the true value with each iteration. Eventually it'll reach the true value assuming we have enough computing resources to continue the iterations

- <b>Note</b>: We can also add "alpha" to control the rate at which we update the weight(to reduce over/under-shooting the updation). "alpha" can be interpreted as the learning rate

# Streetlights problem

## Gradient descent without any hidden layers

### Trying with alpha = 0.1

In [5]:
import numpy as np
weights = np.array([0.5,0.48,-0.7])
alpha = 0.1
streetlights = np.array( [[ 1, 0, 1 ],
 [ 0, 1, 1 ],
 [ 0, 0, 1 ],
 [ 1, 1, 1 ],
 [ 0, 1, 1 ],
 [ 1, 0, 1 ] ] )
walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )
input = streetlights[0] 
goal_prediction = walk_vs_stop[0]
for iteration in range(40):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_prediction = walk_vs_stop[row_index]

        prediction = input.dot(weights)

        error = (goal_prediction - prediction) ** 2
        error_for_all_lights += error

        delta = prediction - goal_prediction
        weights = weights - (alpha * (input * delta))
        print("Prediction:" + str(prediction))
    print("Error:" + str(error_for_all_lights) + "\n")

Prediction:-0.19999999999999996
Prediction:-0.19999999999999996
Prediction:-0.5599999999999999
Prediction:0.6160000000000001
Prediction:0.17279999999999995
Prediction:0.17552
Error:2.6561231104

Prediction:0.14041599999999999
Prediction:0.3066464
Prediction:-0.34513824
Prediction:1.006637344
Prediction:0.4785034751999999
Prediction:0.26700416768
Error:0.9628701776715985

Prediction:0.213603334144
Prediction:0.5347420299776
Prediction:-0.26067345110016
Prediction:1.1319428845096962
Prediction:0.6274723921901568
Prediction:0.25433999330650114
Error:0.5509165866836797

Prediction:0.20347199464520088
Prediction:0.6561967149569552
Prediction:-0.221948503950995
Prediction:1.166258650532124
Prediction:0.7139004922542389
Prediction:0.21471099528371604
Error:0.36445836852222424

Prediction:0.17176879622697283
Prediction:0.7324724146523222
Prediction:-0.19966478845083285
Prediction:1.1697769945341199
Prediction:0.7719890116601171
Prediction:0.17297997428859369
Error:0.2516768662079895

Predictio

### Trying with alpha = 0.01

In [6]:
import numpy as np
weights = np.array([0.5,0.48,-0.7])
alpha = 0.01
streetlights = np.array( [[ 1, 0, 1 ],
 [ 0, 1, 1 ],
 [ 0, 0, 1 ],
 [ 1, 1, 1 ],
 [ 0, 1, 1 ],
 [ 1, 0, 1 ] ] )
walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )
input = streetlights[0] 
goal_prediction = walk_vs_stop[0]
for iteration in range(40):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_prediction = walk_vs_stop[row_index]

        prediction = input.dot(weights)

        error = (goal_prediction - prediction) ** 2
        error_for_all_lights += error

        delta = prediction - goal_prediction
        weights = weights - (alpha * (input * delta))
        print("Prediction:" + str(prediction))
    print("Error:" + str(error_for_all_lights) + "\n")

Prediction:-0.19999999999999996
Prediction:-0.21799999999999997
Prediction:-0.68582
Prediction:0.3152182000000001
Prediction:-0.17308616399999993
Prediction:-0.1515353023599999
Error:3.861893282040811

Prediction:-0.1485045963128
Prediction:-0.14662404173327193
Prediction:-0.6459164809559392
Prediction:0.394615820897681
Prediction:-0.10512471250700073
Prediction:-0.10445016845253541
Error:3.352708880768109

Prediction:-0.1023611650834848
Prediction:-0.08095410492150057
Prediction:-0.6094745728457114
Prediction:0.46672989501849804
Prediction:-0.04257487499498336
Prediction:-0.06231850415456308
Error:2.9256218108072027

Prediction:-0.06107213407147172
Prediction:-0.020489471112823288
Prediction:-0.5761825762241007
Prediction:0.5322189236168611
Prediction:0.015037765599337005
Prediction:-0.024678727045003623
Error:2.5666937055426917

Prediction:-0.02418515250410358
Prediction:0.035225649082841426
Prediction:-0.545756935049359
Prediction:0.5916819345561876
Prediction:0.06814506676055454
Pr

We notice that the error is higher when alpha is lower. This is because we're only iterating through the dataset for 40 times. Lower alpha means the weights are updated slowly. This means it'd require more number of iterations to converge. Let us try to increase the no. of iterations for alpha = 0.01

### Trying with alpha = 0.01 and more no. of iterations

In [7]:
import numpy as np
weights = np.array([0.5,0.48,-0.7])
alpha = 0.01
streetlights = np.array( [[ 1, 0, 1 ],
 [ 0, 1, 1 ],
 [ 0, 0, 1 ],
 [ 1, 1, 1 ],
 [ 0, 1, 1 ],
 [ 1, 0, 1 ] ] )
walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )
input = streetlights[0] 
goal_prediction = walk_vs_stop[0]

# INCREASED ITERATIONS FROM 40 to 500
for iteration in range(500):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_prediction = walk_vs_stop[row_index]

        prediction = input.dot(weights)

        error = (goal_prediction - prediction) ** 2
        error_for_all_lights += error

        delta = prediction - goal_prediction
        weights = weights - (alpha * (input * delta))
        print("Prediction:" + str(prediction))
    print("Error:" + str(error_for_all_lights) + "\n")

Prediction:-0.19999999999999996
Prediction:-0.21799999999999997
Prediction:-0.68582
Prediction:0.3152182000000001
Prediction:-0.17308616399999993
Prediction:-0.1515353023599999
Error:3.861893282040811

Prediction:-0.1485045963128
Prediction:-0.14662404173327193
Prediction:-0.6459164809559392
Prediction:0.394615820897681
Prediction:-0.10512471250700073
Prediction:-0.10445016845253541
Error:3.352708880768109

Prediction:-0.1023611650834848
Prediction:-0.08095410492150057
Prediction:-0.6094745728457114
Prediction:0.46672989501849804
Prediction:-0.04257487499498336
Prediction:-0.06231850415456308
Error:2.9256218108072027

Prediction:-0.06107213407147172
Prediction:-0.020489471112823288
Prediction:-0.5761825762241007
Prediction:0.5322189236168611
Prediction:0.015037765599337005
Prediction:-0.024678727045003623
Error:2.5666937055426917

Prediction:-0.02418515250410358
Prediction:0.035225649082841426
Prediction:-0.545756935049359
Prediction:0.5916819345561876
Prediction:0.06814506676055454
Pr

Prediction:0.9700314202371112
Prediction:0.009387431429944026
Error:0.016036120790142865

Prediction:0.009199682801345144
Prediction:0.9704449206900562
Prediction:-0.09213599514809577
Prediction:1.0734046173142495
Prediction:0.9704892898814511
Prediction:0.009059614644799166
Error:0.015788374950857068

Prediction:0.008878422351903184
Prediction:0.970900123713855
Prediction:-0.09154195587567737
Prediction:1.0729313493417387
Prediction:0.9709389138114999
Prediction:0.008739256101533588
Error:0.015545461913342537

Prediction:0.008564470979502914
Prediction:0.9713470982644594
Prediction:-0.09095174720190793
Prediction:1.0724611315503656
Prediction:0.971380451140182
Prediction:0.00842620090687822
Error:0.015307254284327033

Prediction:0.008257676888740642
Prediction:0.9717860033394222
Prediction:-0.09036534436814475
Prediction:1.0719939444020317
Prediction:0.9718140578282747
Prediction:0.008120297294929649
Error:0.015073628892764038

Prediction:0.007957891349031063
Prediction:0.972216994785

Prediction:-0.0025168140250505094
Error:0.00468264951654917

Prediction:-0.0024664777445495
Prediction:0.9910244812795559
Prediction:-0.052146667788116996
Prediction:1.0415447331175087
Prediction:0.9908945636694957
Prediction:-0.0025457666236180163
Error:0.00462127315844546

Prediction:-0.0024948512911456625
Prediction:0.9911270785752534
Prediction:-0.05181045868471077
Prediction:1.041276875224231
Prediction:0.9909971040861107
Prediction:-0.002573629009573912
Error:0.004560732776086755

Prediction:-0.002522156429382437
Prediction:0.991228119858778
Prediction:-0.051476417235165293
Prediction:1.0410107443697367
Prediction:0.9910981067465593
Prediction:-0.0026004262818912424
Error:0.004501015759738159

Prediction:-0.0025484177562534113
Prediction:0.9913276330520097
Prediction:-0.05114452946411525
Prediction:1.0407463294180772
Prediction:0.991197599097249
Prediction:-0.0026261830163413283
Error:0.00444210973558127

Prediction:-0.0025736593560145085
Prediction:0.9914256455390276
Prediction:

Prediction:1.0165812544619388
Prediction:0.9974731875190377
Prediction:-0.002134574644873863
Error:0.0007294876964250364

Prediction:-0.0020918831519763856
Prediction:0.9975659883466255
Prediction:-0.020678599259414624
Prediction:1.0164743484592986
Prediction:0.9974919676031011
Prediction:-0.0021233260250259484
Error:0.0007201077522525906

Prediction:-0.0020808595045254327
Prediction:0.9975841701063346
Prediction:-0.02054527627321231
Prediction:1.0163681317246542
Prediction:0.9975105768324469
Prediction:-0.002112099655583708
Error:0.0007108485163132213

Prediction:-0.0020698576624720334
Prediction:0.9976021848689787
Prediction:-0.020412812871560434
Prediction:1.0162625998139627
Prediction:0.9975290173040356
Prediction:-0.0021008963985163845
Error:0.000701708431344947

Prediction:-0.0020588784705460536
Prediction:0.9976200347066455
Prediction:-0.02028120351240064
Prediction:1.0161577483118356
Prediction:0.9975472910814
Prediction:-0.002089717090128295
Error:0.0006926859603302423

Predic

Now, we observe that the error we get is the lowest we've gotten from the above 3 runs(alpha=0.1, 0.01, and 0.01 with more iterations)

## Finally, a NN with hidden layers(a.k.a, Deep Neural Network) and backpropagation to solve the streetlights problem

In [8]:
# Fixing a seed for numpy's random generator so that the output would be the same
np.random.seed(7)

In [9]:
def relu(x):
    return (x > 0) * x 
def relu2deriv(output):
    return output>0 
streetlights = np.array( [[ 1, 0, 1 ],
                         [ 0, 1, 1 ],
                         [ 0, 0, 1 ],
                         [ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T
 
alpha = 0.2
hidden_size = 4
weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1
for iteration in range(100):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i+1]
        layer_1 = relu(np.dot(layer_0,weights_0_1))
        layer_2 = np.dot(layer_1,weights_1_2)
        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])
        layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)
    if(iteration % 10 == 9):
        print("Error:" + str(layer_2_error))

Error:0.4821562483484186
Error:0.0034435735575660625
Error:0.0001120722755473073
Error:4.365542956526069e-06
Error:1.6639409896388176e-07
Error:6.3136959726108184e-09
Error:2.393579082487338e-10
Error:9.072720981756764e-12
Error:3.438847004523519e-13
Error:1.3034228627789612e-14


## Trying out NN on a custom dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Source: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
df = pd.read_csv('iris.data', header=None)

In [3]:
df

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

### Splitting the data

In [4]:
x = df.iloc[0:100,[0, 1, 2, 3]].values
y = df.iloc[0:100,4].values
y = np.where(y=='Iris-setosa', 0, 1)

In [15]:
x_train = np.empty((80, 4))
x_test = np.empty((20, 4))
y_train = np.empty(80)
y_test = np.empty(20)
x_train[:40],x_train[40:] = x[:40],x[50:90]
x_test[:10],x_test[10:] = x[40:50],x[90:100]
y_train[:40],y_train[40:] = y[:40],y[50:90]
y_test[:10],y_test[10:] = y[40:50],y[90:100]

In [30]:
x_train[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [33]:
y_train[:5]

array([0., 0., 0., 0., 0.])

In [35]:
def relu(x):
    return (x > 0) * x 
def relu2deriv(output):
    return output>0 
 
alpha = 0.001
hidden_size = 10
weights_0_1 = 2*np.random.random((4,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1
for iteration in range(200):
    layer_2_error = 0
    for i in range(len(x_train)):
        layer_0 = x_train[i:i+1]
        layer_1 = relu(np.dot(layer_0,weights_0_1))
        layer_2 = np.dot(layer_1,weights_1_2)
        layer_2_error += np.sum((layer_2 - y_train[i:i+1]) ** 2)
        layer_2_delta = (layer_2 - y_train[i:i+1])
        layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)
    if(iteration % 5 == 4):
        print("Error:" + str(layer_2_error))

Error:17.787066779863864
Error:5.68119382367085
Error:2.8031298296500693
Error:2.049321577269315
Error:1.781319371285434
Error:1.6333102293812674
Error:1.520552855893836
Error:1.4262721880336031
Error:1.3438447295306004
Error:1.2707938186414574
Error:1.2061751355148265
Error:1.149126581313423
Error:1.0988130651870396
Error:1.0544526209824223
Error:1.0155477711713106
Error:0.9814473614761859
Error:0.9513112785580935
Error:0.9247096805301228
Error:0.9011101604021214
Error:0.8802697280853353
Error:0.8618293035925879
Error:0.8454753578317601
Error:0.8309895171069908
Error:0.8181375680353015
Error:0.8067194012793442
Error:0.7965619441873321
Error:0.7875144835971402
Error:0.7794452666970091
Error:0.7722388524910807
Error:0.7657939494792904
Error:0.7600215982927847
Error:0.7548436176688804
Error:0.7501912621853138
Error:0.7460040560979571
Error:0.7422287766685082
Error:0.7388185659481109
Error:0.7357321537419554
Error:0.732933177220031
Error:0.7303895847644932
Error:0.7280731133638112


As we can see in the above simple NN, the error is decreasing as we train the model more and more. At the end, the error is not decreasing as much so we can think of it like a sort of convergence for the NN. Our final error is a negligible 0.72% or 0.0072

### Final weights of the neurons

In [36]:
weights_0_1

array([[ 0.18922591, -0.37064905, -0.38332266, -0.06093613,  0.52782928,
         0.92584493,  0.70169423,  0.46710895, -0.82670213, -0.77848249],
       [ 0.1253615 , -0.86338363, -0.74934612,  0.55380522,  0.87388262,
         0.70637579,  0.84555486, -0.68506804,  0.56754604, -0.85245338],
       [ 0.17220614,  0.94792035,  0.60600929, -0.90201533, -0.35217241,
         0.24418999, -0.905092  ,  0.45599022, -0.59146915,  0.56429186],
       [-0.72347633, -0.25569211,  0.25247531, -0.58671001,  0.48554333,
        -0.25172697,  0.42856175, -0.7182824 ,  0.14171072,  0.71903842]])

In [38]:
weights_1_2

array([[-0.63718108],
       [-0.38521071],
       [-0.78787769],
       [ 0.22443374],
       [-0.82080688],
       [ 0.74329714],
       [-0.01759583],
       [-0.19866892],
       [ 0.36897802],
       [-0.11754965]])

### Evaluating our NN using the test set

In [94]:
y_pred = np.rint(np.dot(relu(np.dot(x_test, weights_0_1)), weights_1_2))
y_pred

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [97]:
from sklearn.metrics import accuracy_score

In [98]:
accuracy_score(y_test, y_pred)

1.0

Our neural network was successfully able to categorize the datapoints to their classes with 100% accuracy